jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-def:
        BUILD: stack
        STACK_YAML: stack.yaml
      stack-lts-6:
        BUILD: stack
        STACK_YAML: stack-lts-6.yaml
        ARGS: "--resolver lts-6"
      stack-lts-9:
        BUILD: stack
        STACK_YAML: stack-lts-9.yaml
        ARGS: "--resolver lts-9"
      stack-lts-11:
        BUILD: stack
        STACK_YAML: stack-lts-11.yaml
        ARGS: "--resolver lts-11"
      stack-lts-12:
        BUILD: stack
        STACK_YAML: stack-lts-12.yaml
        ARGS: "--resolver lts-12"
      stack-lts-13:
        BUILD: stack
        STACK_YAML: stack.yaml
        ARGS: "--resolver lts-13"
    maxParallel: 3
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack setup $ARGS > /dev/null
      stack --install-ghc $ARGS test --bench --only-dependencies
      stack $ARGS test --bench --no-run-benchmarks
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
